# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W4zxP7Y6QM-HySFdRUMEaoF7b0s5Aia7
"""

def greetings(a):
  a = input().split()
  g = "Доброго времени суток, " + a[0] + ' "Человек" ' + a[1] + "!"
  return g
greetings(a)