# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1thyW67TPURnEnU9v8hBdJPutKmf6dUJT
"""

# №1.4
a = input().split()
otr = 0
bol = 0
chet = 0
for i in a:
  i = int(i)
  if i < 0:
    otr += 1
  if i > 8:
    bol += 1
  if i % 2 == 0:
    chet += 1
print(otr, bol, chet, end = ' ')