# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1thyW67TPURnEnU9v8hBdJPutKmf6dUJT
"""

# №1.2
a = input().split()
mx = int(a[0])
mn = int(a[0])
for i in a:
  i = int(i)
  if mx < i:
    mx = i
  elif mn > i:
    mn = i
print(mn, mx, end = ' ')