# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1thyW67TPURnEnU9v8hBdJPutKmf6dUJT
"""

# №1.1
a = input()
b = a.split()
b[::-1]