# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1thyW67TPURnEnU9v8hBdJPutKmf6dUJT
"""

# № 2.3
a = input()
l = len(a)
k = 0
i = 0
while k < l:
  if a[i].isupper():
    first = a[i]
    n = i
  if a[i].isdigit():
    second = a[i]
    g = a[i + 1]
    n1 = i + 1
    n2 = n1 - n 
    break
  k += 1
  i += 1
b = a[n::n2]
print(b)