# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1thyW67TPURnEnU9v8hBdJPutKmf6dUJT
"""

# №2.1
a = int(input())
l = 0
f = 0
t = 0
while l < a:
  b = input()
  if "True" in b:
    t += 1
  elif "False" in b:
    f += 1
  l += 1
print(t, f, end = ' ')