# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1thyW67TPURnEnU9v8hBdJPutKmf6dUJT
"""

# №1.3
a = input()
b = list(a)
c = len(b)
if c > 6:
  print(b[3], b[5])
else:
  print(a[::-2])